version: '3.8'

services:
  backend:
    build: ./backend
    container_name: study_tracker_backend
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/study_tracker_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - study_tracker_network

  db:
    image: postgres:latest
    container_name: study_tracker_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: study_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - study_tracker_network

volumes:
  postgres_data:

networks:
  study_tracker_network:
    driver: bridge
