services:
  backend:
    build:
      context: .        
      dockerfile: Dockerfile
    container_name: study_tracker_backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - study_tracker_network
    ports:
      - "8000:8000"  # <- AQUI!
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:latest
    container_name: study_tracker_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}     
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - study_tracker_network

volumes:
  postgres_data:

networks:
  study_tracker_network:
    driver: bridge
