version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv  # opcional
      - ENCRYPTION  # opcional
    environment:
      ENCRYPTION: $(openssl rand -hex 16)  # opcional
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase_data:/pb_data
      - ./pocketbase_public:/pb_public  # opcional
      - ./pocketbase_hooks:/pb_hooks  # opcional
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    